-- Team Members: Alyssa Tan, Pravan Kalaga, Maya Holikatti, Raghav Mittal

CREATE TABLE if not exists USER
(
    Email VARCHAR(50) NOT NULL,
    Password INT NOT NULL,
    DateJoined timestamp,
	IsSuspended BOOLEAN NOT NULL,
	IsManager BOOLEAN NOT NULL,
    CONSTRAINT USERPK PRIMARY KEY(Email)
);

CREATE TABLE if not exists REVIEWABLE_ENTITY
(
	SubmittedBy VARCHAR(50),
    EntityID int NOT NULL,
    DateSubmitted timestamp,
    IsPending BOOLEAN NOT NULL,
    CONSTRAINT ENTITYID PRIMARY KEY(EntityID),
    FOREIGN KEY (SubmittedBy) REFERENCES USER(Email) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE if not exists REVIEW
(
	Email VARCHAR(50) NOT NULL,
	EntityID int NOT NULL,
    DateSubmitted timestamp,
	Comment VARCHAR(255),
	Rating int NOT NULL CHECK(Rating >= 1 AND Rating <= 5),
	CONSTRAINT REVPK PRIMARY KEY(Email, EntityID),
    CONSTRAINT REVEMAIL FOREIGN KEY (Email) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT REVID FOREIGN KEY (EntityID) REFERENCES REVIEWABLE_ENTITY(EntityID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE if not exists CITY
(
	CityID int NOT NULL,
	Name varchar(50) NOT NULL,
	Country varchar(50) NOT NULL,
	State varchar(50),
	CONSTRAINT CITYID FOREIGN KEY(CityID) REFERENCES REVIEWABLE_ENTITY(EntityID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CITYPK PRIMARY KEY(CityID)
);

CREATE TABLE if not exists ATTRACTION
(
	AttrID int NOT NULL,
	LocatedIn int NOT NULL,
	Name varchar(50) NOT NULL,
	Address varchar(255) NOT NULL,
	Description varchar(255) NOT NULL,
	PRIMARY KEY(AttrID),
	FOREIGN KEY(AttrID) REFERENCES REVIEWABLE_ENTITY(EntityID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ATTFK FOREIGN KEY(LocatedIn) REFERENCES CITY(CityID)  ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT U_Attraction UNIQUE (Name, Address)
);


CREATE TABLE if not exists CATEGORY
(
    CName VARCHAR(50),
    CONSTRAINT CAT_NAME PRIMARY KEY(CName)
);

CREATE TABLE if not exists FALLS_UNDER
(
	AttrID int,
	Category varchar(50),
    CONSTRAINT CATFK FOREIGN KEY(Category) REFERENCES CATEGORY(CName)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT IDFK FOREIGN KEY(AttrID) REFERENCES ATTRACTION(AttrID)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FUPK PRIMARY KEY(AttrID, Category)
);

CREATE TABLE if not exists HOURS_OF_OPERATION
(
	AttrID int,
	DayOfTheWeek varchar(9) CHECK(DayOfTheWeek IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
	OpenTime time,
	CloseTime time,
    CONSTRAINT OPID FOREIGN KEY(AttrID) REFERENCES ATTRACTION(AttrID)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT OPPK PRIMARY KEY(AttrID, DayOfTheWeek)
);

CREATE TABLE if not exists CONTACT_INFO
(
	AttrID int,
	ContactMethod varchar(50),
	MethodValue varchar(50),
    CONSTRAINT CONTACTID FOREIGN KEY(AttrID) REFERENCES ATTRACTION(AttrID)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CONTACTPK PRIMARY KEY(AttrID, ContactMethod, MethodValue)
);



